pull_request_rules:
  - name: 📦 Automatic merge on @dependabot pull request
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label=dependencies
      - check-success=CodeQL
      - check-success=Vercel
    actions:
      merge:
        method: merge
      comment:
        message: 📦 Automatic merge on @dependabot pull request
  - name: 🤖 Automatic merge on @pull pull request
    conditions:
      - author~=^pull(|-preview)\[bot\]$
      - check-success=CodeQL
      - check-success=Vercel
    actions:
      merge:
        method: merge
      comment:
        message: 🤖 Automatic merge on @pull pull request
